// Generated by scripts/sync-tokens.mjs — do not edit by hand.
// Lantern raw-color scales that differ from the default Tailwind palette.
export default {
  "violet": {
    "50": "#fcfaff",
    "100": "#f9f5ff",
    "200": "#f4ebff",
    "300": "#e9d7fe",
    "400": "#d6bbfb",
    "500": "#b692f6",
    "600": "#9e77ed",
    "700": "#7f56d9",
    "800": "#6941c6",
    "900": "#53389e",
    "950": "#42307d"
  }
};
